
#ifndef FACE_DETECTION_EXPORT_H
#define FACE_DETECTION_EXPORT_H

#ifdef FACE_DETECTION_BUILD_AS_STATIC
#  define FACE_DETECTION_EXPORT
#  define FACE_DETECTION_NO_EXPORT
#else
#  ifndef FACE_DETECTION_EXPORT
#    ifdef face_detection_EXPORTS
        /* We are building this library */
#      define FACE_DETECTION_EXPORT 
#    else
        /* We are using this library */
#      define FACE_DETECTION_EXPORT 
#    endif
#  endif

#  ifndef FACE_DETECTION_NO_EXPORT
#    define FACE_DETECTION_NO_EXPORT 
#  endif
#endif

#ifndef FACE_DETECTION_DEPRECATED
#  define FACE_DETECTION_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef FACE_DETECTION_DEPRECATED_EXPORT
#  define FACE_DETECTION_DEPRECATED_EXPORT FACE_DETECTION_EXPORT FACE_DETECTION_DEPRECATED
#endif

#ifndef FACE_DETECTION_DEPRECATED_NO_EXPORT
#  define FACE_DETECTION_DEPRECATED_NO_EXPORT FACE_DETECTION_NO_EXPORT FACE_DETECTION_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef FACE_DETECTION_NO_DEPRECATED
#    define FACE_DETECTION_NO_DEPRECATED
#  endif
#endif

#endif
